version: '3.1'

services:
  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: example
    ports:
      - 9990:5432

  adminer:
    image: adminer
    ports:
      - 8880:8080
